/*
 * Payment Backend API
 *
 * This file contains REST API specification for payment project. The file is autogenerated from the swagger definition.
 *
 * API version: 0.1.38
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type ApiStatus struct {

	Msg string `json:"msg"`

	Code int32 `json:"code"`

	Data string `json:"data"`
}
