/*
 * EAP Jupyter Backend API
 *
 * This file contains REST API specification for Kubeflow notebooks. The file is autogenerated from the swagger definition.
 *
 * API version: 0.1.38
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"payment_proj/routes"
)



func main() {

	log.Printf("Server started")

	router := routes.NewRouter()

	log.Fatal(router.Run(":8080"))

}
